### PR TITLE
Pagination Bugfixes + QOL Features for the Notes Pages

### PR DESCRIPTION
**Pull request by xPugnocode**
# Pagination Bugfixes + QOL Features for the Notes Pages
## Pagination Bugfix: URL Parameters
- Fixes error raised when visiting notes/add and notes/categories caused by express.js thinking that add and categories was one of the url parameters.
- Fixed by moving `router.get('/:pageNum')` to the bottom of the routes js file.
## QOL Feature: Updated the Next Button
- Prevents next button from appearing in notes page if the next page will be empty.
- Created a new temporary function (newGetPageData) in db.js because I didn't want to mess up the current pagination for /forums.

### CODE REVIEW

**Comment by xPugnocode** [comment]
branch conflicts smh, please read my code before tryna resolve the conflicts

**Comment by xPugnocode** [comment]
please remember the newGetPageData and to change that my previous code has 10 entries per page instead of 5 so update the .pug file as well

**Review by edwinSp1 — COMMENTED** [review]
ayoooo nice the only problem is that you copied newGetPageData twice

**Review by edwinSp1 — APPROVED** [review]
nice

**Pull request merged**
